version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433
      
  web:
    image: yaroslavbutorin/yamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"    
    depends_on:
      - db
    env_file:
      - ./.env
      
  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_value:
  media_value:
